---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 1e8d182abe77f327a462bc45afd486fa28cdbbdf
    app.quarkus.io/build-timestamp: 2021-12-30 - 08:25:33 +0000
  labels:
    app.kubernetes.io/name: mercury-operator
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: mercury-operator
  namespace: mercury
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 1e8d182abe77f327a462bc45afd486fa28cdbbdf
    app.quarkus.io/build-timestamp: 2021-12-30 - 08:25:33 +0000
  labels:
    app.kubernetes.io/name: mercury-operator
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: mercury-operator
  namespace: mercury
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: mercury-operator
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mercury-operator-view
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicedomainclustercontroller-crd-validating-role-binding
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: servicedomaincontroller-crd-validating-role-binding
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: josdk-crd-validating-cluster-role
  namespace: mercury
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicedomainclustercontroller-cluster-role
  namespace: mercury
rules:
  - apiGroups:
      - mercury.redhat.io
    resources:
      - servicedomainclusters
      - servicedomainclusters/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicedomaincontroller-cluster-role
  namespace: mercury
rules:
  - apiGroups:
      - mercury.redhat.io
    resources:
      - servicedomains
      - servicedomains/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicedomainclustercontroller-cluster-role-binding
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: servicedomainclustercontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicedomaincontroller-cluster-role-binding
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: servicedomaincontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 1e8d182abe77f327a462bc45afd486fa28cdbbdf
    app.quarkus.io/build-timestamp: 2021-12-30 - 08:25:33 +0000
  labels:
    app.kubernetes.io/name: mercury-operator
    app.kubernetes.io/version: 1.0.1-SNAPSHOT
  name: mercury-operator
  namespace: mercury
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mercury-operator
      app.kubernetes.io/version: 1.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 1e8d182abe77f327a462bc45afd486fa28cdbbdf
        app.quarkus.io/build-timestamp: 2021-12-30 - 08:25:33 +0000
      labels:
        app.kubernetes.io/name: mercury-operator
        app.kubernetes.io/version: 1.0.1-SNAPSHOT
      namespace: mercury
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ecosystem-appeng/mercury-operator:1.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: mercury-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccount: mercury-operator
